<a href="https://colab.research.google.com/github/dhruvilmaniar/PracticalTF/blob/master/TensorOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Broadcasting**

Brodcasting is used to make the two tensors used in the computation into compatible size.

Say you want to add two tensors having different rank, different ndim.

In such case, broadcasting may help us as follows:
* It adds extra dimension into smaller ndim tensor to match the ndim of the larger tensor. This axis is known as broadcasting axis.
* The smaller tensor is then repeated multiple times to match the dimensions of the first tensor.

In [0]:
import numpy as np

In [2]:
x = np.random.rand(32,10)
y = np.random.rand(10,)

print(x.ndim, x.shape)
print(y.ndim, y.shape)

2 (32, 10)
1 (10,)


In [3]:
y = np.expand_dims(y, axis=0)
print(y.ndim, y.shape)
# after completing the first bullet, shape is:

2 (1, 10)


In [4]:
y = np.repeat(y, 32, axis = 0)
print(y.ndim, y.shape)

2 (32, 10)


In [0]:
print(x+y)

**However, numpy does this for us:**

In [6]:
x = np.random.rand(32,10)
y = np.random.rand(10)
print((x+y).shape)

(32, 10)


# **Tensor Reshaping**

Tensor reshaping is mainly used in data pre processing. It is generally used to modify the tensor to match the other tensor's shape.

In [9]:
x = np.random.rand(5,2)

print(x.ndim, x.shape)
print(x)

2 (5, 2)
[[0.27066153 0.98105153]
 [0.71927129 0.20549047]
 [0.59830151 0.25837115]
 [0.4129494  0.10804189]
 [0.29173388 0.74524165]]


In [11]:
# Reshaping (5,2) to (10,) matrix:

x = x.reshape((10,1))
print(x.ndim, x.shape)
print(x)

2 (10, 1)
[[0.27066153]
 [0.98105153]
 [0.71927129]
 [0.20549047]
 [0.59830151]
 [0.25837115]
 [0.4129494 ]
 [0.10804189]
 [0.29173388]
 [0.74524165]]


**Transpose of a Tensor**

It is the same as it sounds. It converts rows into columns and columns into rows.

In [15]:
x = np.random.rand(5,2)
print(x.ndim, x.shape)
print(x)
x = np.transpose(x)
print(x.ndim, x.shape)
print(x)

2 (5, 2)
[[0.58802859 0.91225148]
 [0.0328415  0.3816977 ]
 [0.84210579 0.11335989]
 [0.36423349 0.73491587]
 [0.22402632 0.20096492]]
2 (2, 5)
[[0.58802859 0.0328415  0.84210579 0.36423349 0.22402632]
 [0.91225148 0.3816977  0.11335989 0.73491587 0.20096492]]
