<a href="https://colab.research.google.com/github/dhruvilmaniar/PracticalTF/blob/master/TensorOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Broadcasting**

Brodcasting is used to make the two tensors used in the computation into compatible size.

Say you want to add two tensors having different rank, different ndim.

In such case, broadcasting may help us as follows:
* It adds extra dimension into smaller ndim tensor to match the ndim of the larger tensor. This axis is known as broadcasting axis.
* The smaller tensor is then repeated multiple times to match the dimensions of the first tensor.

In [0]:
import numpy as np

In [0]:
x = np.random.rand(32,10)
y = np.random.rand(10,)

print(x.ndim, x.shape)
print(y.ndim, y.shape)

2 (32, 10)
1 (10,)


In [0]:
y = np.expand_dims(y, axis=0)
print(y.ndim, y.shape)
# after completing the first bullet, shape is:

2 (1, 10)


In [0]:
y = np.repeat(y, 32, axis = 0)
print(y.ndim, y.shape)

2 (32, 10)


In [0]:
print(x+y)

**However, numpy does this for us:**

In [0]:
x = np.random.rand(32,10)
y = np.random.rand(10)
print((x+y).shape)

(32, 10)


# **Tensor Reshaping**

Tensor reshaping is mainly used in data pre processing. It is generally used to modify the tensor to match the other tensor's shape.

In [0]:
x = np.random.rand(5,2)

print(x.ndim, x.shape)
print(x)

2 (5, 2)
[[0.27066153 0.98105153]
 [0.71927129 0.20549047]
 [0.59830151 0.25837115]
 [0.4129494  0.10804189]
 [0.29173388 0.74524165]]


In [0]:
# Reshaping (5,2) to (10,) matrix:

x = x.reshape((10,1))
print(x.ndim, x.shape)
print(x)

2 (10, 1)
[[0.27066153]
 [0.98105153]
 [0.71927129]
 [0.20549047]
 [0.59830151]
 [0.25837115]
 [0.4129494 ]
 [0.10804189]
 [0.29173388]
 [0.74524165]]


**Transpose of a Tensor**

It is the same as it sounds. It converts rows into columns and columns into rows.

In [0]:
x = np.random.rand(5,2)
print(x.ndim, x.shape)
print(x)
x = np.transpose(x)
print(x.ndim, x.shape)
print(x)

2 (5, 2)
[[0.58802859 0.91225148]
 [0.0328415  0.3816977 ]
 [0.84210579 0.11335989]
 [0.36423349 0.73491587]
 [0.22402632 0.20096492]]
2 (2, 5)
[[0.58802859 0.0328415  0.84210579 0.36423349 0.22402632]
 [0.91225148 0.3816977  0.11335989 0.73491587 0.20096492]]


# **Tensors and Numpy Arrays**

A tensor is a multi-dimensional array, similar to numpy ndarrays.
tf.Tensor objects have a datatype and a shape like numpy ndarrays. Additionally,
tf.Tensors can reside in accelerator's memory, and also can be used to perform operations such as tf.add, tf.matmul, tf.square etc.

These operations produces and requires the data to be a tensor object, however,
These operations automatically converts native python types and numpy objects into tensors. For ex:

In [3]:
%tensorflow_version 2.x

import tensorflow as tf

TensorFlow 2.x selected.


In [7]:
# We can add two scalers just by typing:

print(tf.add(3,6))
# returns tf.Tensor(9, shape = (), dtype = int)

tf.Tensor(9, shape=(), dtype=int32)


In [8]:
# In the same manner, we can add two vectors as follows:
print(tf.add([1,4],[2,7]))
# returns tf.Tensor([3,11], shape = (2,), dtype = int)

tf.Tensor([ 3 11], shape=(2,), dtype=int32)


In [9]:
#  Tensor operations:

print(tf.square(5))
# returns tf.Tensor(25, shape=(), dtype=int)

print(tf.square([2,6]))
# returns tf.Tensor([4,36], shape=(2,), dtype = int)

tf.Tensor(25, shape=(), dtype=int32)
tf.Tensor([ 4 36], shape=(2,), dtype=int32)


In [13]:
# Sum all the elements in the tensor:

print(tf.reduce_sum([2,4,65,7,3]))
# returns tf.Tensor(x, shape=(), dtype = int), x = sum of elements in array

tf.Tensor(81, shape=(), dtype=int32)


In [14]:
# Operator overloading:

print(tf.square(5) + tf.square(2))
# returns tf.Tensor(29, shape = (), dtype= int)

tf.Tensor(29, shape=(), dtype=int32)


**Matrix Multiplication:**

In [34]:
x = np.array([[1]])
y = np.array([[6,7]])
print(x.shape, x.ndim)
print(y.shape, y.ndim)

z = tf.matmul(x,y)
print(z)
print(z.shape, z.ndim)

x = np.array([[1,2,4,3],[1,6,6,3]])
y = np.array([[1],[3],[5],[3]])
print(x.shape, x.ndim)
print(y.shape, y.ndim)

z = tf.matmul(x,y)
print(z)

(1, 1) 2
(1, 2) 2
tf.Tensor([[6 7]], shape=(1, 2), dtype=int64)
(1, 2) 2
(2, 4) 2
(4, 1) 2
tf.Tensor(
[[36]
 [58]], shape=(2, 1), dtype=int64)


**The main two differences between Tensors and Numpy Arrays are:**
1. Tensor operations can be accelerated by Hardware Accelerators (GPUs, TPUs).
2. Tensors are immutable.

**Tensors and Numpy Compatiblity:**

Tensors and Numpy arrays are easily converted to one-another automatically, because they share the same underlying memory allocation. Due to this, the conversation is also cheap.


---


However, we can convert Tensor into numpy array explicitly by using .numpy() method.

Also, sharing the same underlying memory is not always possible, since tensors can be stored inside the accelerator's memory.

In case the tf.Tensor is hosted in GPU, first we have to make a copy into CPU and then carry out the conversion into numpy.

In [43]:
# Let's take a numpy array and use tensor operations on that:
a = np.ones([3,3])
print(a)
print(a.shape, a.ndim)
print()

# Using tensor operations on Numpy array:
y = tf.add(a, np.ones([3,3]))
print(y)
print(y.shape, y.ndim)
print()

z = tf.square(y)
print(z)
print()

# Using numpy operations on tensors:
# Also, if you notice, numpy will perform brodcasting operation to the second argument.
w = np.add(z, np.random.uniform([3,3,3]))
print(w)
print(w.shape, w.ndim)
print()

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3) 2

tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]], shape=(3, 3), dtype=float64)
(3, 3) 2

tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]], shape=(3, 3), dtype=float64)

[[6.57984027 6.44788527 6.40278275]
 [6.57984027 6.44788527 6.40278275]
 [6.57984027 6.44788527 6.40278275]]
(3, 3) 2

